import numpy as np, time, os, itertools
from scipy.linalg import null_space
exec(open('e6tw.py').read().split('if __name__ == "__main__":')[0])
E, F = np.load(f"e6rep_w{omega}.npy", allow_pickle=True)
t0 = time.time(); I = np.eye(n); N2 = n*n
Kd = {i: K(i) for i in range(5)}; Ki = {i: np.linalg.inv(Kd[i]) for i in range(5)}
dE = {i: np.kron(E[i], I) + np.kron(Kd[i], E[i]) for i in range(1, 5)}
dF = {i: np.kron(F[i], Ki[i]) + np.kron(I, F[i]) for i in range(1, 5)}
WW = (W[:, None, :] + W[None, :, :]).reshape(N2, 4)
wk = lambda w: tuple(np.round(np.asarray(w)*2).astype(int))
wsp = {}
for idx, w in enumerate(WW): wsp.setdefault(wk(w), []).append(idx)
hws = {}
for key, idx in wsp.items():
    ns = null_space(np.vstack([dE[i][:, idx] for i in range(1, 5)]), rcond=1e-10)
    if ns.shape[1]:
        vs = []
        for c_ in range(ns.shape[1]):
            v = np.zeros(N2, complex); v[idx] = ns[:, c_]; vs.append(v)
        hws[key] = vs
sk = {i: wk(simple[i]) for i in range(1, 5)}
def descend(v, key0):
    """words (tuples of f-indices) giving a basis of the module generated by v"""
    words = {key0: [()]}; vecs = {key0: v[:, None]}; frontier = [key0]
    while frontier:
        new = []
        for key in frontier:
            for wd, col in zip(words[key], vecs[key].T):
                for i in range(1, 5):
                    k2 = tuple(a - b for a, b in zip(key, sk[i]))
                    y = dF[i] @ col
                    if np.linalg.norm(y) < 1e-10: continue
                    cur = vecs.get(k2)
                    Z = y[:, None] if cur is None else np.hstack([cur, y[:, None]])
                    if np.linalg.matrix_rank(Z, tol=1e-8*np.linalg.norm(Z)) > (0 if cur is None else cur.shape[1]):
                        vecs[k2] = Z; words.setdefault(k2, []).append(wd + (i,)); new.append(k2)
        frontier = list(set(new))
    return words
def apply_word(v, wd):
    for i in wd: v = dF[i] @ v
    return v
types = []
for key, vs in hws.items():
    words = descend(vs[0], key)
    dim = sum(len(w) for w in words.values())
    basis = [np.array([apply_word(v, wd) for k_ in sorted(words) for wd in words[k_]]).T for v in vs]
    types.append(dict(key=key, mult=len(vs), dim=dim, hw=vs, B=basis))
types.sort(key=lambda t: (-t['dim'], t['mult']))
print("components (dim x multiplicity):", [(t['dim'], t['mult']) for t in types], " total", sum(t['dim']*t['mult'] for t in types), f"[{time.time()-t0:.0f}s]")
Ball = np.hstack([B for t in types for B in t['B']]); Binv = np.linalg.inv(Ball)
offs = []; o = 0
for t in types:
    oo = []
    for B in t['B']: oo.append((o, o + B.shape[1])); o += B.shape[1]
    offs.append(oo)
# unknowns: for each type a mult x mult matrix M_t (entry [beta, alpha]); normalise M of the largest type = 1
unk = [(ti, b, a) for ti, t in enumerate(types) for a in range(t['mult']) for b in range(t['mult'])]
uidx = {u: k for k, u in enumerate(unk)}
def R_apply_cols(v):
    """columns: d(R v)/d(unknown) for R = sum_t M_t acting on component copies"""
    c = Binv @ v; cols = np.zeros((N2, len(unk)), complex)
    for ti, t in enumerate(types):
        for a in range(t['mult']):
            s, e_ = offs[ti][a]; ca = c[s:e_]
            if np.abs(ca).max() < 1e-14: continue
            for b in range(t['mult']):
                cols[:, uidx[(ti, b, a)]] += t['B'][b] @ ca
    return cols
def solve_R(x):
    blocks = []
    ops = [(np.kron(x*E[0], I) + np.kron(Kd[0], E[0]), np.kron(E[0], I) + np.kron(Kd[0], x*E[0])),
           (np.kron(F[0]/x, Ki[0]) + np.kron(I, F[0]), np.kron(F[0], Ki[0]) + np.kron(I, F[0]/x))]
    for (Xa, Xb) in ops:
        for ti, t in enumerate(types):
            for a, v in enumerate(t['hw']):
                L = R_apply_cols(Xa @ v)
                Rv = np.zeros((N2, len(unk)), complex)
                for b in range(t['mult']): Rv[:, uidx[(ti, b, a)]] += t['hw'][b]
                blocks.append(L - Xb @ Rv)
    Mx = np.vstack(blocks)
    sol, *_ = np.linalg.lstsq(Mx[:, 1:], -Mx[:, 0], rcond=None); u = np.concatenate([[1.0], sol])
    return u, np.abs(Mx @ u).max()/np.abs(Mx).max()
def Rmatrix(u):
    cols = np.zeros((N2, N2), complex)
    for ti, t in enumerate(types):
        for a in range(t['mult']):
            s, e_ = offs[ti][a]
            cols[:, s:e_] = sum(u[uidx[(ti, b, a)]]*t['B'][b] for b in range(t['mult']))
    return cols @ Binv
u, res = solve_R(0.83+0.29j); print(f"16-parameter R-matrix solve: residual {res:.1e}  [{time.time()-t0:.0f}s]")
# check: R commutes with Delta(f_4) and intertwines e_0 at another x
x1 = 0.61-0.77j; u1, _ = solve_R(x1); R1 = Rmatrix(u1)
c1 = max(np.abs(R1 @ dE[i] - dE[i] @ R1).max() for i in range(1, 5))
e0a = np.kron(x1*E[0], I) + np.kron(Kd[0], E[0]); e0b = np.kron(E[0], I) + np.kron(Kd[0], x1*E[0])
print(f"full R-matrix: commutes with U_q(f_4) to {c1:.0e}; e_0 intertwining {np.abs(R1 @ e0a - e0b @ R1).max()/np.abs(R1).max():.0e}")
np.save(f"e6R_setup_w{omega}.npy", np.array([0]), allow_pickle=True)
# special points: poles and residue ranks along x = eps q^-l
def Rx(x): return Rmatrix(solve_R(x)[0])
found = []
for eps, nm in ((1, '+'), (-1, '-'), (1j, '+i'), (-1j, '-i')):
    for l in range(1, 25):
        xs = eps*q**(-l); n1 = np.linalg.norm(Rx(xs*(1 + 1e-5))); n2 = np.linalg.norm(Rx(xs*(1 + 1e-7)))
        if n2/n1 > 30:
            sv = np.linalg.svd(1e-7*Rx(xs*(1 + 1e-7)), compute_uv=False); found.append((nm, l, int(np.sum(sv > 1e-6*sv[0]))))
print("R-matrix poles (x = eps q^-l) and residue ranks:", found, f"[{time.time()-t0:.0f}s]")
